[{"info": "<p>Sofia is the capital and largest city of Bulgaria. Sofia is located at the foot of Mount Vitosha in the western part of the country. It occupies a strategic position at the centre of the Balkan Peninsula. Sofia's history spans 2,400 years.</p>",
  "lat": 42.6544, 
  "long": 23.3649, 
  "title": "Sofia, Bulgaria", 
  "color": "green"},
  {"info": "<p>Bucharest is the capital municipality, cultural, industrial, and financial centre of Romania. It is the largest city in Romania, located in the southeast of the country.</p>",
   "lat": 44.4167, 
   "long": 26.1000, 
   "title": "Bucharest, Romania", 
   "color": "yellow"},
  {"info": "<p>Skopje is the capital and largest city of the Republic of Macedonia. It is the country's political, cultural, economic, and academic center. It was known in the Roman period under the name Scupi.</p>",
   "lat": 42.0000, 
   "long": 21.4333, 
   "title": "Skopje, Macedonia", 
   "color": "red"},
  {"info": "<p>Athens is the capital and largest city of Greece. Athens dominates the Attica region and is one of the world's oldest cities, with its recorded history spanning around 3,400 years.</p>",
   "lat": 37.9778, 
   "long": 23.7278, 
   "title": "Vienna (Wien), Austria", 
   "color": "blue"},
  {"info": "<p>Satellite view is showing Madrid, largest city, economical and political center and the national capital of  Spain, The city is located on a high plateau in the center of the country at the Manzanares river. In Madrid's metropolitan area (urban area and suburbs) there live almost 6 million people. </p>",
   "lat": 40.41114339950097, 
   "long": -3.6879730224609375, 
   "title": "Madrid, Spain", 
   "color": "purple"},  
  {"info": "<p>According to tradition, the ancient city was founded by Romulus (after whom it is named) in 753 bc on the Palatine Hill; as it grew it spread to the other six hills of Rome. Since 1871 Rome is the capital of a unified Italy.</p>",
   "lat": 41.89001042401827, 
   "long": 12.490425109863281, 
   "title": "Rome (Roma), Italy", 
   "color": "pink"}]